### ISSUE TITLE
libraw.pc and libraw_r.pc not installed

### ISSUE THREAD

**Issue by gaaned92** [LibRaw/LibRaw-cmake#31]
Building last snapshot of libraw under MSYS2/MINGW64, I notice that libraw.pc and libraw_r.pc are neither build or installed in lib/pkgconfig.
These two files should be generated on the basis of the templates located in  ./libraw/cmake.
Do I miss something? 
I would like it to be automated, but I am not able to add/modify commands in  CMakeLists.txt.

For the present I generated the files by hand.
Thanks

**Comment by kmilos** [comment]
I think this was being skipped just on MinGW, should now be fixed by #33.

I've also updated the templates a bit to match the original project a bit better. I think there might be dependencies missing if doing static linkage, but I'll leave that to someone else to handle, pkgconfig is not my forte I must say...
